CREATE TABLE "users" (
  "id" bigserial PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "hashed_password" varchar NOT NULL,
  "full_name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "user_role" varchar NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "user_categories" (
  "user_id" int NOT NULL,
  "category" varchar NOT NULL,
  PRIMARY KEY ("user_id", "category")
);

CREATE TABLE "issues" (
  "id" bigserial PRIMARY KEY,
  "volume" int NOT NULL,
  "number" int NOT NULL,
  "publish_date" date NOT NULL
);

CREATE TABLE "articles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "abstract" text NOT NULL,
  "file_path" text NOT NULL,
  "subject" varchar NOT NULL,
  "status" varchar NOT NULL DEFAULT 'submitted',
  "author_id" int NOT NULL,
  "issue_id" int,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "reviews" (
  "id" bigserial PRIMARY KEY,
  "article_id" int NOT NULL,
  "reviewer_id" int NOT NULL,
  "comments" text NOT NULL,
  "feedback_file_path" text,
  "decision" varchar,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE INDEX ON "articles" ("author_id");

CREATE INDEX ON "articles" ("issue_id");

CREATE INDEX ON "reviews" ("article_id");

CREATE INDEX ON "reviews" ("reviewer_id");

COMMENT ON COLUMN "users"."user_role" IS 'author, reviewer, admin';

COMMENT ON TABLE "user_categories" IS 'Each user can have multiple fields of expertise';

COMMENT ON COLUMN "reviews"."decision" IS 'accept, revise, reject';

ALTER TABLE "user_categories" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "articles" ADD FOREIGN KEY ("author_id") REFERENCES "users" ("id");

ALTER TABLE "articles" ADD FOREIGN KEY ("issue_id") REFERENCES "issues" ("id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("article_id") REFERENCES "articles" ("id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("reviewer_id") REFERENCES "users" ("id");
