// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: author.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (
  title, abstract, file_path, subject,
  status, author_id, issue_id, created_at
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7, $8
) RETURNING id, title, abstract, file_path, subject, status, author_id, issue_id, created_at
`

type CreateArticleParams struct {
	Title     string        `json:"title"`
	Abstract  string        `json:"abstract"`
	FilePath  string        `json:"file_path"`
	Subject   string        `json:"subject"`
	Status    string        `json:"status"`
	AuthorID  int32         `json:"author_id"`
	IssueID   sql.NullInt32 `json:"issue_id"`
	CreatedAt time.Time     `json:"created_at"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, createArticle,
		arg.Title,
		arg.Abstract,
		arg.FilePath,
		arg.Subject,
		arg.Status,
		arg.AuthorID,
		arg.IssueID,
		arg.CreatedAt,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Abstract,
		&i.FilePath,
		&i.Subject,
		&i.Status,
		&i.AuthorID,
		&i.IssueID,
		&i.CreatedAt,
	)
	return i, err
}

const getArticleByID = `-- name: GetArticleByID :one
SELECT id, title, abstract, file_path, subject, status, author_id, issue_id, created_at FROM articles WHERE id = $1
`

func (q *Queries) GetArticleByID(ctx context.Context, id int32) (Article, error) {
	row := q.db.QueryRowContext(ctx, getArticleByID, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Abstract,
		&i.FilePath,
		&i.Subject,
		&i.Status,
		&i.AuthorID,
		&i.IssueID,
		&i.CreatedAt,
	)
	return i, err
}

const getArticlesByAuthor = `-- name: GetArticlesByAuthor :many
SELECT id, title, abstract, file_path, subject, status, author_id, issue_id, created_at FROM articles WHERE author_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetArticlesByAuthor(ctx context.Context, authorID int32) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, getArticlesByAuthor, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Abstract,
			&i.FilePath,
			&i.Subject,
			&i.Status,
			&i.AuthorID,
			&i.IssueID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmittedArticles = `-- name: ListSubmittedArticles :many
SELECT id, title, abstract, file_path, subject, status, author_id, issue_id, created_at FROM articles WHERE status = 'submitted' ORDER BY created_at DESC
`

func (q *Queries) ListSubmittedArticles(ctx context.Context) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, listSubmittedArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Abstract,
			&i.FilePath,
			&i.Subject,
			&i.Status,
			&i.AuthorID,
			&i.IssueID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
