// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: category.sql

package db

import (
	"context"
)

const addUserCategory = `-- name: AddUserCategory :exec
INSERT INTO user_categories (user_id, category) VALUES ($1, $2)
`

type AddUserCategoryParams struct {
	UserID   int32  `json:"user_id"`
	Category string `json:"category"`
}

func (q *Queries) AddUserCategory(ctx context.Context, arg AddUserCategoryParams) error {
	_, err := q.db.ExecContext(ctx, addUserCategory, arg.UserID, arg.Category)
	return err
}

const findReviewersByCategory = `-- name: FindReviewersByCategory :many
SELECT u.id, u.username, u.hashed_password, u.full_name, u.email, u.user_role, u.created_at
FROM users u
JOIN user_categories c ON u.id = c.user_id
WHERE c.category = $1 AND u.user_role = 'reviewer'
`

func (q *Queries) FindReviewersByCategory(ctx context.Context, category string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, findReviewersByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.HashedPassword,
			&i.FullName,
			&i.Email,
			&i.UserRole,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserCategories = `-- name: GetUserCategories :many
SELECT category FROM user_categories WHERE user_id = $1
`

func (q *Queries) GetUserCategories(ctx context.Context, userID int32) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUserCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
