// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: issue.sql

package db

import (
	"context"
	"time"
)

const createIssue = `-- name: CreateIssue :one
INSERT INTO issues (
  volume, issue_number, publish_date
) VALUES (
  $1, $2, $3
) RETURNING id, volume, issue_number, publish_date
`

type CreateIssueParams struct {
	Volume      int32     `json:"volume"`
	IssueNumber int32     `json:"issue_number"`
	PublishDate time.Time `json:"publish_date"`
}

func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, createIssue, arg.Volume, arg.IssueNumber, arg.PublishDate)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.Volume,
		&i.IssueNumber,
		&i.PublishDate,
	)
	return i, err
}

const getIssueByID = `-- name: GetIssueByID :one
SELECT id, volume, issue_number, publish_date FROM issues WHERE id = $1
`

func (q *Queries) GetIssueByID(ctx context.Context, id int64) (Issue, error) {
	row := q.db.QueryRowContext(ctx, getIssueByID, id)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.Volume,
		&i.IssueNumber,
		&i.PublishDate,
	)
	return i, err
}

const getLatestIssue = `-- name: GetLatestIssue :one
SELECT id, volume, issue_number, publish_date FROM issues ORDER BY publish_date DESC LIMIT 1
`

func (q *Queries) GetLatestIssue(ctx context.Context) (Issue, error) {
	row := q.db.QueryRowContext(ctx, getLatestIssue)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.Volume,
		&i.IssueNumber,
		&i.PublishDate,
	)
	return i, err
}

const listIssues = `-- name: ListIssues :many
SELECT id, volume, issue_number, publish_date FROM issues ORDER BY publish_date DESC
`

func (q *Queries) ListIssues(ctx context.Context) ([]Issue, error) {
	rows, err := q.db.QueryContext(ctx, listIssues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Issue
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.Volume,
			&i.IssueNumber,
			&i.PublishDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
