// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Article struct {
	ID               int32         `json:"id"`
	Title            string        `json:"title"`
	Abstract         string        `json:"abstract"`
	FilePath         string        `json:"file_path"`
	ArticleSubject   string        `json:"article_subject"`
	SubmissionStatus string        `json:"submission_status"`
	AuthorID         int32         `json:"author_id"`
	IssueID          sql.NullInt32 `json:"issue_id"`
	CreatedAt        time.Time     `json:"created_at"`
}

type Issue struct {
	ID          int64     `json:"id"`
	Volume      int32     `json:"volume"`
	IssueNumber int32     `json:"issue_number"`
	PublishDate time.Time `json:"publish_date"`
}

type Review struct {
	ID               int64          `json:"id"`
	ArticleID        int32          `json:"article_id"`
	ReviewerID       int32          `json:"reviewer_id"`
	Comments         string         `json:"comments"`
	FeedbackFilePath sql.NullString `json:"feedback_file_path"`
	// accept, revise, reject
	Decision  sql.NullString `json:"decision"`
	CreatedAt time.Time      `json:"created_at"`
}

type User struct {
	ID             int64  `json:"id"`
	Username       string `json:"username"`
	HashedPassword string `json:"hashed_password"`
	FullName       string `json:"full_name"`
	Email          string `json:"email"`
	// author, reviewer, admin
	UserRole  string    `json:"user_role"`
	CreatedAt time.Time `json:"created_at"`
}

// Each user can have multiple fields of expertise
type UserCategory struct {
	UserID   int32  `json:"user_id"`
	Category string `json:"category"`
}
