// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: review.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countDecisions = `-- name: CountDecisions :one
SELECT decision, COUNT(*) FROM reviews
WHERE article_id = $1 GROUP BY decision
`

type CountDecisionsRow struct {
	Decision sql.NullString `json:"decision"`
	Count    int64          `json:"count"`
}

func (q *Queries) CountDecisions(ctx context.Context, articleID int32) (CountDecisionsRow, error) {
	row := q.db.QueryRowContext(ctx, countDecisions, articleID)
	var i CountDecisionsRow
	err := row.Scan(&i.Decision, &i.Count)
	return i, err
}

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (
  article_id, reviewer_id, comments,
  feedback_file_path, decision, created_at
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, article_id, reviewer_id, comments, feedback_file_path, decision, created_at
`

type CreateReviewParams struct {
	ArticleID        int32          `json:"article_id"`
	ReviewerID       int32          `json:"reviewer_id"`
	Comments         string         `json:"comments"`
	FeedbackFilePath sql.NullString `json:"feedback_file_path"`
	Decision         sql.NullString `json:"decision"`
	CreatedAt        time.Time      `json:"created_at"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, createReview,
		arg.ArticleID,
		arg.ReviewerID,
		arg.Comments,
		arg.FeedbackFilePath,
		arg.Decision,
		arg.CreatedAt,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.ReviewerID,
		&i.Comments,
		&i.FeedbackFilePath,
		&i.Decision,
		&i.CreatedAt,
	)
	return i, err
}

const getReviewsByReviewer = `-- name: GetReviewsByReviewer :many
SELECT id, article_id, reviewer_id, comments, feedback_file_path, decision, created_at FROM reviews WHERE reviewer_id = $1
`

func (q *Queries) GetReviewsByReviewer(ctx context.Context, reviewerID int32) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, getReviewsByReviewer, reviewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.ReviewerID,
			&i.Comments,
			&i.FeedbackFilePath,
			&i.Decision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewsForArticle = `-- name: GetReviewsForArticle :many
SELECT id, article_id, reviewer_id, comments, feedback_file_path, decision, created_at FROM reviews WHERE article_id = $1
`

func (q *Queries) GetReviewsForArticle(ctx context.Context, articleID int32) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, getReviewsForArticle, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.ReviewerID,
			&i.Comments,
			&i.FeedbackFilePath,
			&i.Decision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
